# Generated by Django 3.2.4 on 2021-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_banners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['created'], 'verbose_name': 'Banners', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterField(
            model_name='banners',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Clave'),
        ),
    ]
